//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
namespace Silicus.UtilityContainer.Models.DataObjects
{
    public partial class EngagementRole
    {
        public int ID { get; set; }
        public int EngagementID { get; set; }
        public Nullable<int> ResourceHistoryID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsBooked { get; set; }
        public string Description { get; set; }
        public Nullable<int> OverridenTitleID { get; set; }
    }
}
