//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silicus.Encourage.Models.DataObjects
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nomination
    {
        public Nomination()
        {
            this.ManagerComments = new HashSet<ManagerComment>();
            this.ReviewerComments = new HashSet<ReviewerComment>();
            this.Winners = new HashSet<Winner>();
        }
    
        public int Id { get; set; }
        public int AwardId { get; set; }
        public int ManagerId { get; set; }
        public int ProjectID { get; set; }
        public int UserId { get; set; }
        public bool IsPLC { get; set; }
        public Nullable<System.DateTime> NominationDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Award Award { get; set; }
        public virtual ICollection<ManagerComment> ManagerComments { get; set; }
        public virtual ICollection<ReviewerComment> ReviewerComments { get; set; }
        public virtual ICollection<Winner> Winners { get; set; }
    }
}
