//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EngagementTaskTypes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EngagementTaskTypes()
        {
           
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }
        public int EngagementID { get; set; }
        public string TaskType { get; set; }
        public int StandardTaskTypeID { get; set; }
        public bool IsDescriptionRequired { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> IsTaskType { get; set; }
        public Nullable<int> IsTask { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<bool> CanLinkedWithTickets { get; set; }
    
        public virtual Engagement Engagement { get; set; }
    }
}
