//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class    Resource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Resource()
        {
           
        }
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int ID { get; set; }
        public int UserID { get; set; }
        public bool IsTimecardsRequireApproval { get; set; }
        public Nullable<int> DirectManager1ID { get; set; }
        public bool CanDirectManager1ApproveTime { get; set; }
        public bool CanDirectManager1ApproveSkills { get; set; }
        public Nullable<int> DirectManager2ID { get; set; }
        public bool CanDirectManager2ApproveTime { get; set; }
        public bool CanDirectManager2ApproveSkills { get; set; }
        public bool IsShared { get; set; }
        public Nullable<System.DateTime> SkillsLastUpdatedOn { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public Nullable<System.DateTime> RehireDate { get; set; }
    }
}
