//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Data.Entity.ModelConfiguration.Conventions;

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UtilityContainerEntities : DbContext
    {
        public UtilityContainerEntities()
            : base("name=UtilityContainerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Conventions.Remove<PluralizingTableNameConvention>();
            //throw new UnintentionalCodeFirstException();
        }
        
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Engagement> Engagements { get; set; }
        public virtual DbSet<EngagementRoles> EngagementRoles { get; set; }
        public virtual DbSet<EngagementTaskTypes> EngagementTaskTypes { get; set; }
        public virtual DbSet<EngagementType> EngagementTypes { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<ResourceHistory> ResourceHistories { get; set; }
        public virtual DbSet<ResourceSkillLevel> ResourceSkillLevels { get; set; }
        public virtual DbSet<ResourceType> ResourceTypes { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Title> Titles { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
