//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateGraphProgressDetail
    {
        public int CandProgDetID { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<double> PersonalDetailsPercentage { get; set; }
        public Nullable<double> ContactDetailsPercentage { get; set; }
        public Nullable<double> EducationDetailsPercentage { get; set; }
        public Nullable<double> EmploymentDetailsPercentage { get; set; }
        public Nullable<double> FamilyDetailsPercentage { get; set; }
        public Nullable<double> UploadDcoumentsPercentage { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
