//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationDocumentCategoryMapping
    {
        public int EduDocCatID { get; set; }
        public int DocumentID { get; set; }
        public int EducationCategoryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Master_EducationCategory Master_EducationCategory { get; set; }
        public virtual Master_Document Master_Document { get; set; }
    }
}
