//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EducationCategoryUniversityBoardMapping
    {
        public int EduCatUNiBodID { get; set; }
        public int EducationCategoryID { get; set; }
        public int UniversityID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Master_EducationCategory Master_EducationCategory { get; set; }
        public virtual Master_University Master_University { get; set; }
    }
}
