//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeProfessionalDetail
    {
        public long EmpProfID { get; set; }
        public long UserID { get; set; }
        public Nullable<int> TotalExprInYears { get; set; }
        public Nullable<int> TotalExprInMonths { get; set; }
        public int DepartmentID { get; set; }
        public int DesignationID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual Master_Department Master_Department { get; set; }
        public virtual Master_Designation Master_Designation { get; set; }
    }
}
