//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeMaster
    {
        public long Id { get; set; }
        public string EmpNo { get; set; }
        public string EmployeeName { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public Nullable<int> Active { get; set; }
        public string ReasonForleaving { get; set; }
        public long UserId { get; set; }
        public Nullable<System.DateTime> LeavingDate { get; set; }
        public Nullable<int> RelReason_id { get; set; }
    }
}
