//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmploymentDetail
    {
        public long EmploymentDetID { get; set; }
        public long UserID { get; set; }
        public string EmployementNo { get; set; }
        public string CompanyName { get; set; }
        public string CompanyAddress { get; set; }
        public int CompanyCityID { get; set; }
        public Nullable<int> CurrencyID { get; set; }
        public string OtherCompanyCity { get; set; }
        public int CompanyStateID { get; set; }
        public string OtherCompanyState { get; set; }
        public int CompanyCountryID { get; set; }
        public string CompanyZipcode { get; set; }
        public string CompanyPhoneNumber { get; set; }
        public string CompanyWebsite { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public string JobTitle { get; set; }
        public string Designation { get; set; }
        public string PreviousEmpId { get; set; }
        public string CTC { get; set; }
        public string ReasonForLeave { get; set; }
        public string SupervisorName { get; set; }
        public string SupervisorDesignation { get; set; }
        public string SupervisorEmail { get; set; }
        public string SupervisorPhone { get; set; }
        public string HRName { get; set; }
        public string HREmail { get; set; }
        public string HRPhone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCurrentEmployment { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual EmploymentDetail EmploymentDetails1 { get; set; }
        public virtual EmploymentDetail EmploymentDetail1 { get; set; }
        public virtual Master_City Master_City { get; set; }
        public virtual Master_Country Master_Country { get; set; }
        public virtual Master_Currency Master_Currency { get; set; }
        public virtual Master_State Master_State { get; set; }
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
