//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeePersonalDetail
    {
        public long PerDetID { get; set; }
        public long UserID { get; set; }
        public string FatherName { get; set; }
        public string PlaceofBirth { get; set; }
        public int MaritalStatID { get; set; }
        public int BloodGroup { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string PANNumber { get; set; }
        public string PassportNumber { get; set; }
        public string SecurityNumber { get; set; }
        public string AadharCardNumber { get; set; }
        public string UANNumber { get; set; }
        public string MotherTongue { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public string EmpNo { get; set; }
        public string EmpEmail { get; set; }
        public string MaidenName { get; set; }
        public string OtherName { get; set; }
        public string DateofBirth { get; set; }
        public string EthnicCode { get; set; }
        public string Gender { get; set; }
        public string SpouseName { get; set; }
        public string HavePassport { get; set; }
        public string NameOnPassport { get; set; }
        public Nullable<System.DateTime> PassportExpiryDate { get; set; }
        public string OtherPlaceOfBirth { get; set; }
        public Nullable<int> NumberOfEmployments { get; set; }
    
        public virtual Master_Bloodgroup Master_Bloodgroup { get; set; }
        public virtual Master_Country Master_Country { get; set; }
        public virtual Master_MaritalStatus Master_MaritalStatus { get; set; }
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
