//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeEducationDetail
    {
        public long EduDetID { get; set; }
        public long UserID { get; set; }
        public int EducationCategoryID { get; set; }
        public string OtherEducationCategory { get; set; }
        public int DisciplineID { get; set; }
        public string OtherDiscipline { get; set; }
        public int UniversityID { get; set; }
        public string OtherUniversityName { get; set; }
        public int CollegeID { get; set; }
        public string OtherCollegeName { get; set; }
        public string InstituteAddress { get; set; }
        public int PassingYear { get; set; }
        public string RollNumber { get; set; }
        public string Percentage { get; set; }
        public int SpecializationID { get; set; }
        public string OtherSpecialization { get; set; }
        public int ClassID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string BreaksDuringEducation { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
        public virtual Master_Class Master_Class { get; set; }
        public virtual Master_College Master_College { get; set; }
        public virtual Master_Discipline Master_Discipline { get; set; }
        public virtual Master_EducationCategory Master_EducationCategory { get; set; }
        public virtual Master_Specialization Master_Specialization { get; set; }
        public virtual Master_University Master_University { get; set; }
    }
}
