//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoginDetail()
        {
            this.AdminEducationCategoryForUsers = new HashSet<AdminEducationCategoryForUser>();
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.EmployeeContactDetails = new HashSet<EmployeeContactDetail>();
            this.EmployeeFamilyDetails = new HashSet<EmployeeFamilyDetail>();
            this.EmployeePersonalDetails = new HashSet<EmployeePersonalDetail>();
            this.EmploymentDetails = new HashSet<EmploymentDetail>();
            this.WelcomeNoteDetails = new HashSet<WelcomeNoteDetail>();
            this.CandidateChangeRequestsDetails = new HashSet<CandidateChangeRequestsDetail>();
            this.CandidateGraphProgressDetails = new HashSet<CandidateGraphProgressDetail>();
            this.EmployeeEducationDetails = new HashSet<EmployeeEducationDetail>();
            this.EmploymentCounts = new HashSet<EmploymentCount>();
        }
    
        public long UserID { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string Email { get; set; }
        public string EmpNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> JoiningDate { get; set; }
        public string CountryCode { get; set; }
        public string ContactNumber { get; set; }
        public string RequisitionID { get; set; }
        public string JoiningLocation { get; set; }
        public string ProjectName { get; set; }
        public string PrimarySkill { get; set; }
        public string OnboardingSPOCName { get; set; }
        public string RecruiterName { get; set; }
        public int DepartmentID { get; set; }
        public int DesignationID { get; set; }
        public int RoleID { get; set; }
        public Nullable<System.DateTime> ActivatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<int> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<bool> IsFresher { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AdminEducationCategoryForUser> AdminEducationCategoryForUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeContactDetail> EmployeeContactDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeFamilyDetail> EmployeeFamilyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeePersonalDetail> EmployeePersonalDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentDetail> EmploymentDetails { get; set; }
        public virtual Master_Department Master_Department { get; set; }
        public virtual Master_Designation Master_Designation { get; set; }
        public virtual Master_Role Master_Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WelcomeNoteDetail> WelcomeNoteDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateChangeRequestsDetail> CandidateChangeRequestsDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateGraphProgressDetail> CandidateGraphProgressDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeEducationDetail> EmployeeEducationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmploymentCount> EmploymentCounts { get; set; }
       
    }
}
