//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_SubDocumentsCategory
    {
        public int SubDocCatID { get; set; }
        public int DocCatID { get; set; }
        public string SubDocCategoryName { get; set; }
        public Nullable<bool> IsNeeded { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual Master_DocumentCategory Master_DocumentCategory { get; set; }
    }
}
