//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master_Document()
        {
            this.DocumentDetails = new HashSet<DocumentDetail>();
            this.EducationDocumentCategoryMappings = new HashSet<EducationDocumentCategoryMapping>();
        }
    
        public int DocumentID { get; set; }
        public Nullable<int> DocCatID { get; set; }
        public string Document { get; set; }
        public Nullable<bool> IsNeeded { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocumentDetail> DocumentDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EducationDocumentCategoryMapping> EducationDocumentCategoryMappings { get; set; }
        public virtual Master_DocumentCategory Master_DocumentCategory { get; set; }
    }
}
