//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test_CandidateChangeRequestsDetails
    {
        public long CandChangeReqID { get; set; }
        public long UserID { get; set; }
        public string FieldName { get; set; }
        public string FieldValue { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
    
        public virtual LoginDetail LoginDetail { get; set; }
    }
}
