//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silicus.Encourage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EnCourageEntities3 : DbContext
    {
        public EnCourageEntities3()
            : base("name=EnCourageEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<AwardCriteria> AwardCriterias { get; set; }
        public virtual DbSet<Criterion> Criteria { get; set; }
        public virtual DbSet<FrequencyMaster> FrequencyMasters { get; set; }
        public virtual DbSet<ManagerComment> ManagerComments { get; set; }
        public virtual DbSet<Nomination> Nominations { get; set; }
        public virtual DbSet<Reviewer> Reviewers { get; set; }
        public virtual DbSet<ReviewerComment> ReviewerComments { get; set; }
        public virtual DbSet<Winner> Winners { get; set; }
    }
}
