//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_User
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string ApplicationAuthUserID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string DisplayName { get; set; }
        public string EmailAddress { get; set; }
        public string EmployeeID { get; set; }
        public string FirstName { get; set; }
        public Nullable<System.DateTime> InactiveDate { get; set; }
        public string Initials { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string MobilePhone { get; set; }
        public string OfficePhone { get; set; }
        public bool OverrideTimeZone { get; set; }
        public int PrimaryRoleID { get; set; }
        public int TimezoneID { get; set; }
        public string UserName { get; set; }
    }
}
