//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_TimeCard
    {
        public int ID { get; set; }
        public int TimeCardResourceTaskTypeID { get; set; }
        public int ResourceID { get; set; }
        public int EngagementTaskTypeID { get; set; }
        public int TimeCardStatusID { get; set; }
        public System.DateTime Date { get; set; }
        public decimal Hours { get; set; }
        public bool IsValid { get; set; }
    }
}
