//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_TKT_RosterCalenderInfo
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public int QueueID { get; set; }
        public int RosterTypeMasterID { get; set; }
        public Nullable<int> RosterShiftID { get; set; }
    }
}
