//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_ResourceWorkingScheduleHistory
    {
        public int ID { get; set; }
        public int ResourceID { get; set; }
        public int ResourceHistoryID { get; set; }
        public int WeekDayID { get; set; }
        public bool IsOverrideLocationSchedule { get; set; }
        public bool IsWorkingDay { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<decimal> Duration { get; set; }
    }
}
