//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_TKT_RosterCalenderUsers
    {
        public int ID { get; set; }
        public int RosterCalenderInfoID { get; set; }
        public int UserID { get; set; }
        public bool IsOnCall { get; set; }
    }
}
