//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_EngagementTaskTypes
    {
        public int ID { get; set; }
        public int EngagementID { get; set; }
        public string TaskType { get; set; }
        public int StandardTaskTypeID { get; set; }
        public bool IsDescriptionRequired { get; set; }
        public bool IsActive { get; set; }
        public int DisplayOrder { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> IsTaskType { get; set; }
        public Nullable<int> IsTask { get; set; }
        public Nullable<int> TaskTypeID { get; set; }
        public Nullable<bool> CanLinkedWithTickets { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<decimal> PlannedEfforts { get; set; }
        public Nullable<decimal> Size { get; set; }
    }
}
