//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_TimeCardResourceEngagements
    {
        public int ID { get; set; }
        public int ResourceID { get; set; }
        public int EngagementID { get; set; }
        public int EngagementRoleID { get; set; }
        public bool IsVisible { get; set; }
    }
}
