//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_EngagementRolesSchedule
    {
        public int ID { get; set; }
        public int EngagementRoleID { get; set; }
        public int FillModeID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> ContractHours { get; set; }
        public Nullable<decimal> BookedHours { get; set; }
        public Nullable<decimal> RequestedHours { get; set; }
        public Nullable<bool> IsOpenRequest { get; set; }
    }
}
