//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_TimeCardResourceTaskTypes
    {
        public int ID { get; set; }
        public int TimeCardResourceEngagementsID { get; set; }
        public int TaskTypeID { get; set; }
        public bool IsVisible { get; set; }
    }
}
