//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityDataSyncLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwExt_Engagement
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int ClientID { get; set; }
        public string Code { get; set; }
        public int EngagementTypeID { get; set; }
        public string Stage { get; set; }
        public int LocationID { get; set; }
        public int EngagementManagerID { get; set; }
        public int PrimaryProjectManagerID { get; set; }
        public System.DateTime BeginDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public Nullable<decimal> HoursPerDay { get; set; }
        public string Description { get; set; }
        public bool IsOpenForTime { get; set; }
        public string TimeApprover { get; set; }
        public Nullable<int> TimeApproverID { get; set; }
        public Nullable<int> IndustryManagerID { get; set; }
        public Nullable<int> SalesAccountManagerID { get; set; }
        public Nullable<int> GeneralManagerID { get; set; }
    }
}
